<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Pages\About-us.html" />
    <Content Include="Pages\basket.html" />
    <Content Include="Pages\Contacts.html" />
    <Content Include="Pages\Home.html" />
    <Content Include="Pages\index.html" />
    <Content Include="Pages\Making-an-order.html" />
    <Content Include="Pages\thank-you-page.html" />
    <Content Include="Pages\Сatalog.html" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\favicon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Telegram.Bot" Version="21.10.1" />
  </ItemGroup>

</Project>
